fishing:
  x: 828
  y: 254
  width: 151
  height: 476
  timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 0.6
      max: 0.8
    pause:
      min: 0.5
      max: 1.5
    cast:
      min: 1.2
      max: 1.8
repairing:
  x: 855
  y: 508
  length: 25
  every: 500
  enable: 1
  timeouts:
    arm_disarm:
      min: 1
      max: 1.5
    inventory:
      min: 1
      max: 1.5
    repair:
      min: 1
      max: 1.5
    confirm:
      min: 1
      max: 1.5
    move_around:
      min: 0.5
      max: 1.0
bait:
  bait_x: 1280
  bait_y: 572
  equip_button_x: 1550
  equip_button_y: 815
  length: 25
  enable: 1
  timeouts:
    select:
      min: 0.9
      max: 1.4
    confirm:
      min: 0.9
      max: 1.4
colors:
  green:
    r: 4
    g: 227
    b: 162
  brown:
    r: 230
    g: 110
    b: 22
  red:
    r: 109
    g: 18
    b: 21
resolution:
  x: 5120
  y: 2160
log_lvl: DEBUG
